Simple example for computing item-item similarities for Collaborative filtering as adopted from https://towardsdatascience.com/user-to-user-vs-item-to-item-collaborative-filtering-explained-through-simple-examples-part-1-f133bec23a58

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({'u1':[5,1,4],'u2':[1,5,1]},index=['m1','m2','m3'])
df

    u1  u2
m1   5   1
m2   1   5
m3   4   1

In [6]:
# computing item-item similarity between the three movies
from sklearn.metrics.pairwise import cosine_similarity
df_cs = pd.DataFrame(data=cosine_similarity(df),
                     columns=['m1','m2','m3'],
                     index=['m1','m2','m3'])
df_cs

          m1        m2        m3
m1  1.000000  0.384615  0.998868
m2  0.384615  1.000000  0.428086
m3  0.998868  0.428086  1.000000

A common approach to normalizing how “difficult a reviewer” a user may be in comparison to other users is to normalize their ratings by subtracting the average value and dividing the ratings by the range.

In [8]:
def normalize(row):
    row_norm = (row-row.mean())/(row.max()-row.min())
    return row_norm

df_norm = df.apply(normalize)
df_norm

          u1        u2
m1  0.416667 -0.333333
m2 -0.583333  0.666667
m3  0.166667 -0.333333

In [9]:
# Compute cosine similarity on normalizing
def normalize(row):
    row_norm = (row-row.mean())/(row.max()-row.min())
    return row_norm

df_norm = df.apply(normalize)

df_cs_norm = pd.DataFrame(data=cosine_similarity(df_norm),
                          columns=['m1','m2','m3'],
                          index=['m1','m2','m3'])

df_cs_norm

          m1        m2        m3
m1  1.000000 -0.984337  0.907959
m2 -0.984337  1.000000 -0.967617
m3  0.907959 -0.967617  1.000000

In [10]:
df_transpose = df.T
df_transpose.corr(method='pearson')

     m1   m2   m3
m1  1.0 -1.0  1.0
m2 -1.0  1.0 -1.0
m3  1.0 -1.0  1.0